'use client';

import { useEffect as reactUseEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowDown, BedDouble, CalendarDays, CarFront, Check, CheckCircle2, ChevronRight, CookingPot, ExternalLink, Home, LampDesk, MapPin, MapPinned, Moon, Mountain, ParkingCircle, Route, ShieldAlert, Sparkles, Sunset, Trees, Users, X } from 'lucide-react';
import { Checkbox } from '@/components/ui/checkbox';
import { budgetCategories, BudgetScenario, routeStops, scenarioTotals, trip } from '@/lib/trip-data';

const useEffect = (effect: () => unknown, dependencies: React.DependencyList) =>
  reactUseEffect(() => {
    effect();
  }, dependencies);

const days = [
  { day:'FRI', date:'SEP 04', title:'Night departure', label:'Tampa → Tennessee', tone:'night', items:[
    { time:'8:00 PM', title:'Leave Tampa', meta:'Kia Carnival · 5 travelers', icon:CarFront, kind:'drive' },
    { time:'OVERNIGHT', title:'Drive north', meta:'Rotate alert drivers · breaks required', icon:Moon, kind:'night' },
  ]},
  { day:'SAT', date:'SEP 05', title:'Recover + Smokies', label:'Cosby / Great Smoky Mountains', tone:'forest', items:[
    { time:'MORNING', title:'Arrive in Tennessee', meta:'Arrival time is approximate', icon:MapPin, kind:'drive' },
    { time:'4–5 HOURS', title:'Mandatory recovery sleep', meta:'Real rest before any trail decision', icon:BedDouble, kind:'sleep', strong:true },
    { time:'AFTER REST', title:'Alum Cave Bluffs', meta:'4.6 mi round trip · timing flexible', icon:Mountain, kind:'hike' },
    { time:'NIGHT', title:'Tiny Home on the River', meta:'Cosby, TN · $177', icon:Home, kind:'stay' },
  ]},
  { day:'SUN', date:'SEP 06', title:'McAfee at sunset', label:'Cosby → Catawba / Roanoke', tone:'sunset', items:[
    { time:'MORNING', title:'Drive toward Virginia', meta:'Exact departure remains flexible', icon:CarFront, kind:'drive' },
    { time:'4–6 HOURS', title:'McAfee Knob', meta:'7.5 mi · reach overlook before sunset', icon:Sunset, kind:'sunset', strong:true },
    { time:'AFTER DARK', title:'Headlamp descent', meta:'One real headlamp per person', icon:LampDesk, kind:'night' },
    { time:'NIGHT', title:'Roanoke 2BR home', meta:'Roanoke area · $155', icon:Home, kind:'stay' },
  ]},
  { day:'MON', date:'SEP 07', title:'The long way home', label:'Roanoke → Tampa', tone:'return', items:[
    { time:'MORNING', title:'Breakfast + reset', meta:'No major hike planned', icon:CookingPot, kind:'rest' },
    { time:'DAYTIME', title:'Return to Tampa', meta:'Drive time is intentionally flexible', icon:Route, kind:'drive', strong:true },
    { time:'RENTAL', title:'Return Kia Carnival', meta:'Confirm return window avoids extra day', icon:CheckCircle2, kind:'alert' },
  ]},
];

const hikes = [
  { id:'alum', eyebrow:'SATURDAY · PRIMARY', title:'Alum Cave Bluffs', place:'Great Smoky Mountains NP', distance:'4.6 mi', time:'3–4 hr', difficulty:'Moderate', view:'8.6', crowd:'Very high', parking:'Difficult', sunset:'Not planned', description:'Old-growth forest, mountain streams and Arch Rock lead to a dramatic 75–80 ft rock overhang. The trail gets considerably steeper after Arch Rock.', accent:'forest' },
  { id:'mcafee', eyebrow:'SUNDAY · MAIN EVENT', title:'McAfee Knob', place:'Catawba, Virginia', distance:'~7.5 mi', time:'4–6 hr', difficulty:'Moderate', view:'9.7', crowd:'High', parking:'Strategy required', sunset:'Goal', description:'An iconic Appalachian Trail overlook with a broad panorama over Catawba Valley. Arrive well before sunset; descend after dark with proper headlamps.', accent:'sunset' },
];

const stays = [
  { night:'SATURDAY NIGHT', title:'Tiny Home on the River', subtitle:'WATERFALL RUSH', location:'Cosby, Tennessee', date:'Sep 5 → Sep 6', price:177, amenities:['River setting','Tiny home','Near Smokies'], icon:Trees },
  { night:'SUNDAY NIGHT', title:'Roanoke 2BR Mountain Home', subtitle:'MINIMALIST HOME', location:'Roanoke, Virginia area', date:'Sep 6 → Sep 7', price:155, amenities:['Mountain views','Fire pit + grill','Full kitchen','Laundry','Workspace'], icon:Home },
];

const alerts = [
  { level:'critical', icon:Moon, title:'Overnight drive', text:'Friday’s 8 PM departure makes Saturday recovery sleep mandatory before hiking.', status:'Non-negotiable' },
  { level:'warn', icon:ParkingCircle, title:'Smokies parking', text:'Alum Cave is extremely crowded. A parking tag is required over 15 minutes; arrive early or investigate a shuttle.', status:'Needs plan' },
  { level:'critical', icon:Sunset, title:'McAfee sunset', text:'The 7 AM–7 PM shuttle will not cover the post-sunset return. A legal self-parking strategy is required.', status:'Unresolved' },
  { level:'warn', icon:LampDesk, title:'Five headlamps', text:'Bring one real headlamp per person. Do not rely on phone flashlights for the descent.', status:'0 of 5 packed' },
  { level:'note', icon:CarFront, title:'Rental return', text:'Confirm taxes, fees and the Kia Carnival return time so the trip does not trigger another rental day.', status:'Not finalized' },
];

const packing = ['5 headlamps','Hiking shoes','Hydration','Electrolytes','Trail snacks','Rain shells','Portable batteries','First-aid kit','Sunscreen','Bug spray','Change of clothes','Toiletries','Cooler','Water','Phone cables','Offline maps'];

function SectionHead({ eyebrow, title, detail }:{ eyebrow:string; title:string; detail:string }) { return <div className="section-head"><div><p className="section-kicker">{eyebrow}</p><h2>{title}</h2></div><p>{detail}</p></div>; }

function RouteMap() { return <div className="route-map" aria-label="Stylized route map from Tampa to the Smokies, McAfee Knob, Roanoke, and back to Tampa"><div className="map-topline"><span><MapPinned size={15}/> Road trip route</span><span className="approx-label">APPROXIMATE</span></div><svg className="route-svg" viewBox="0 0 100 100" role="img" aria-label="Five-stop trip route"><path className="contour c1" d="M-4 35 C14 22 22 41 40 29 S72 5 104 22"/><path className="contour c2" d="M-4 55 C22 35 31 60 53 45 S82 20 105 39"/><path className="contour c3" d="M2 76 C28 55 45 85 68 60 S90 42 105 56"/><path className="route-shadow" d="M20 80 C31 72 34 51 47 43 C58 37 65 25 75 23 C79 24 82 31 84 38 C77 61 57 83 30 86"/><path className="route-line" d="M20 80 C31 72 34 51 47 43 C58 37 65 25 75 23 C79 24 82 31 84 38 C77 61 57 83 30 86"/></svg>{routeStops.map(stop=><div className={`route-stop stop-${stop.marker.toLowerCase()}`} style={{left:`${stop.x}%`,top:`${stop.y}%`}} key={stop.marker}><span className="marker">{stop.marker}</span><span className="stop-copy"><strong>{stop.title}</strong><small>{stop.detail}</small></span></div>)}<div className="map-legend"><span><Moon size={13}/> Overnight north</span><span><CarFront size={13}/> Return Monday</span></div></div>; }

function Timeline() { return <div className="timeline-grid">{days.map((day,index)=><article className={`day-card ${day.tone}`} key={day.day}><div className="day-top"><span className="day-index">0{index+1}</span><div><p>{day.day}</p><strong>{day.date}</strong></div></div><h3>{day.title}</h3><p className="day-route">{day.label}</p><div className="day-events">{day.items.map((item,i)=>{const Icon=item.icon;return <div className={`event ${item.kind} ${item.strong?'strong':''}`} key={item.title}><span className="event-icon"><Icon size={15}/></span><div><time>{item.time}</time><strong>{item.title}</strong><small>{item.meta}</small></div>{i<day.items.length-1&&<span className="event-line"/>}</div>})}</div></article>)}</div>; }

function Hikes() { const [stretch,setStretch]=useState(false); return <section className="content-section" id="hikes"><SectionHead eyebrow="02 · TRAILS" title="Two hikes. One stretch call." detail="The plan protects recovery on Saturday and keeps Sunday’s sunset objective explicit."/><div className="hike-grid">{hikes.map(hike=><article className={`hike-card ${hike.accent}`} key={hike.id}><div className="hike-art"><div className="hike-lines"/><span>{hike.eyebrow}</span><Mountain size={42}/><div><h3>{hike.title}</h3><p><MapPin size={13}/>{hike.place}</p></div></div><div className="hike-body"><div className="hike-metrics"><div><span>DISTANCE</span><strong>{hike.distance}</strong></div><div><span>TIME</span><strong>{hike.time}</strong></div><div><span>DIFFICULTY</span><strong>{hike.difficulty}</strong></div></div><p>{hike.description}</p><dl className="ratings"><div><dt>View score</dt><dd>{hike.view}<small>/ 10</small></dd></div><div><dt>Crowd level</dt><dd>{hike.crowd}</dd></div><div><dt>Parking</dt><dd>{hike.parking}</dd></div><div><dt>Sunset</dt><dd>{hike.sunset}</dd></div></dl></div></article>)}</div><article className={`stretch-card ${stretch?'selected':''}`}><div className="stretch-mark"><Sparkles size={18}/></div><div><p>STRETCH OPTION · SATURDAY</p><h3>Mt. LeConte via Alum Cave</h3><span>10 miles round trip · challenging · only if fully rested and timing works</span></div><button onClick={()=>setStretch(!stretch)} aria-pressed={stretch}>{stretch?<><Check size={14}/> Considering</>:<>Keep as option <ChevronRight size={14}/></>}</button></article></section>; }

function Lodging() { return <section className="content-section" id="stays"><SectionHead eyebrow="03 · WHERE WE SLEEP" title="Two simple mountain stays." detail="$332 total lodging · $66.40 per person for the weekend."/><div className="lodging-grid">{stays.map((stay,index)=>{const Icon=stay.icon;return <article className="stay-card" key={stay.title}><div className="stay-visual"><span>{String(index+1).padStart(2,'0')}</span><Icon size={48}/><div className="mini-contours"/></div><div className="stay-body"><div className="stay-label"><span>{stay.night}</span><span>1 NIGHT</span></div><h3>{stay.title}</h3><p className="stay-subtitle">{stay.subtitle}</p><p className="stay-location"><MapPin size={14}/>{stay.location}</p><div className="amenities">{stay.amenities.map(a=><span key={a}>{a}</span>)}</div><div className="stay-bottom"><div><small>{stay.date}</small><strong>${stay.price} total <span>· ${(stay.price/5).toFixed(2)} each</span></strong></div><button aria-label={`View details for ${stay.title}`}><ExternalLink size={15}/></button></div></div></article>})}</div></section>; }

function Budget() { const [scenario,setScenario]=useState<BudgetScenario>('expected'); const [travelers,setTravelers]=useState(5); const total=scenarioTotals[scenario]; const perPerson=Math.round(total/travelers); const categories=useMemo(()=>budgetCategories.map(c=>({...c,value:c[scenario]})),[scenario]); const transport=categories.filter(c=>['vehicle','gas','parking'].includes(c.id)).reduce((a,c)=>a+c.value,0); return <section className="budget-section" id="budget"><div className="content-section budget-inner"><SectionHead eyebrow="04 · MONEY" title="The whole trip, split cleanly." detail="Static planning estimates. Rental taxes and possible extra fees are not finalized."/><div className="scenario-bar" role="group" aria-label="Budget scenario">{(['best','expected','worst'] as BudgetScenario[]).map(s=><button className={scenario===s?'active':''} onClick={()=>setScenario(s)} key={s}>{s==='worst'?'Worst reasonable':s}<span>${scenarioTotals[s].toLocaleString()}</span></button>)}</div><div className="budget-dashboard"><div className="budget-main"><div className="budget-numbers"><div><span>TOTAL TRIP</span><strong key={total}>${total.toLocaleString()}</strong><small>{scenario} case estimate</small></div><div><span>PER PERSON</span><strong key={perPerson}>${perPerson}</strong><small>split by {travelers}</small></div></div><div className="stacked-bar" aria-label="Cost breakdown">{categories.map(c=><span style={{width:`${c.value/total*100}%`,background:c.color}} title={`${c.label}: $${c.value}`} key={c.id}/>)}</div><div className="cost-list">{categories.map(c=><div key={c.id}><span><i style={{background:c.color}}/>{c.label}{c.id==='vehicle'&&<em>ESTIMATE</em>}</span><strong>${c.value}</strong></div>)}</div></div><aside className="split-panel"><p>SPLIT CALCULATOR</p><label>Travelers <span><button onClick={()=>setTravelers(Math.max(1,travelers-1))} aria-label="Remove traveler">−</button><b>{travelers}</b><button onClick={()=>setTravelers(Math.min(12,travelers+1))} aria-label="Add traveler">+</button></span></label><div className="split-result"><span>Each person pays</span><strong>${perPerson}</strong></div><div className="subtotals"><p><span>Lodging</span><b>$332</b></p><p><span>Transportation</span><b>${transport}</b></p><p><span>Food</span><b>${categories.find(c=>c.id==='food')?.value}</b></p></div><div className="budget-callout"><ShieldAlert size={19}/><div><strong>Budget $250–$300</strong><span>per person for a safer cushion</span></div></div></aside></div></div></section>; }

function Logistics() { return <section className="content-section" id="logistics"><SectionHead eyebrow="05 · DO NOT MISS" title="Five things can make or break the weekend." detail="Resolve the parking and rental items before departure. The sleep and headlamp rules are fixed."/><div className="alert-grid">{alerts.map(alert=>{const Icon=alert.icon;return <article className={`alert-card ${alert.level}`} key={alert.title}><div className="alert-icon"><Icon size={19}/></div><div><div className="alert-top"><h3>{alert.title}</h3><span>{alert.status}</span></div><p>{alert.text}</p></div></article>})}</div><div className="parking-note"><AlertTriangle size={18}/><p><strong>McAfee parking:</strong> Route 311 roadside parking is prohibited. Main trailhead capacity is limited, and alternate legal parking adds distance. Do not improvise parking at sunset.</p></div></section>; }

function Packing() { const [checked,setChecked]=useState<string[]>([]); const [loaded,setLoaded]=useState(false); useEffect(()=>{try{setChecked(JSON.parse(localStorage.getItem('mountain-run-packing')||'[]'))}catch{}setLoaded(true)},[]); useEffect(()=>{if(loaded)localStorage.setItem('mountain-run-packing',JSON.stringify(checked))},[checked,loaded]); const toggle=(item:string,value:boolean)=>setChecked(old=>value?[...new Set([...old,item])]:old.filter(x=>x!==item)); return <section className="packing-section" id="packing"><div className="content-section"><div className="packing-head"><div><p className="section-kicker">06 · PACKING</p><h2>Ready means {packing.length}/{packing.length}.</h2><p>Your checklist saves automatically on this device.</p></div><div className="packing-progress"><strong>{checked.length}</strong><span>of {packing.length} packed</span><div><i style={{width:`${checked.length/packing.length*100}%`}}/></div></div></div><div className="packing-grid">{packing.map(item=><label className={checked.includes(item)?'checked':''} key={item}><Checkbox checked={checked.includes(item)} onCheckedChange={value=>toggle(item,Boolean(value))}/><span>{item}</span>{checked.includes(item)&&<Check size={14}/>}</label>)}</div>{checked.length>0&&<button className="clear-button" onClick={()=>setChecked([])}><X size={13}/> Clear checklist</button>}</div></section>; }

export default function HomePage() { const [dark,setDark]=useState(true); useEffect(()=>document.documentElement.classList.toggle('dark',dark),[dark]); return <main><header className="site-header"><a className="brand" href="#top" aria-label="Labor Day Mountain Run home"><span className="brand-mark"><Mountain size={17}/></span><span>Mountain Run <small>LDW ’26</small></span></a><nav aria-label="Trip sections"><a href="#itinerary">Itinerary</a><a href="#hikes">Hikes</a><a href="#stays">Stays</a><a href="#budget">Budget</a><a href="#packing">Packing</a></nav><button className="theme-button" onClick={()=>setDark(v=>!v)} aria-label={`Switch to ${dark?'light':'dark'} mode`}><Moon size={16}/><span>{dark?'Dark':'Light'}</span></button></header><section className="hero" id="top"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/>4 DAYS · LABOR DAY WEEKEND</div><h1>{trip.title}</h1><p className="route-title">{trip.subtitle}</p><p className="lede">Two mountain hikes. Two overnight stays. One ambitious loop through the southern Appalachians.</p><div className="hero-actions"><a className="primary-button" href="#itinerary">View itinerary <ArrowDown size={16}/></a><a className="secondary-button" href="#budget">Budget <span>~$220 / person</span></a></div><dl className="hero-facts"><div><dt><CalendarDays size={15}/>Dates</dt><dd>{trip.dateRange}</dd></div><div><dt><Users size={15}/>Crew</dt><dd>{trip.travelers} travelers</dd></div><div><dt><CarFront size={15}/>Vehicle</dt><dd>{trip.vehicle}</dd></div></dl></div><RouteMap/></section><section className="stat-strip" aria-label="Trip summary"><div><strong>$220</strong><span>Expected / person</span></div><div><strong>{trip.routeMiles}</strong><span>Approx. road miles</span></div><div><strong>2</strong><span>Primary hikes</span></div><div><strong>5</strong><span>Friends</span></div></section><section className="content-section" id="itinerary"><SectionHead eyebrow="01 · THE PLAN" title="Four days. Every critical handoff visible." detail="Timing remains approximate where bookings and exact drive windows are not confirmed."/><Timeline/></section><Hikes/><Lodging/><Budget/><Logistics/><Packing/><footer><div><span className="brand-mark"><Mountain size={17}/></span><p><strong>Labor Day Mountain Run</strong><small>Tampa → Smokies → McAfee Knob → Tampa</small></p></div><p>Sept 4–7, 2026 · Plan responsibly. Hike safely.</p></footer></main>; }
